{{- if include "medplum.shouldDeployGCPIngress" . }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Values.gcp.backendConfig.name | default "medplum-backendconfig" }}
  namespace: {{ include  "medplum.namespace" . }}
  labels:
    {{- include "medplum.labels" . | nindent 4 }}
spec:
  securityPolicy:
    name: {{ .Values.gcp.backendConfig.securityPolicyName | default "ingress-security-policy" }}
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /healthcheck 
  logging:
    enable: true
    sampleRate: 0.5
{{- end }}

