{{- if .Values.deployment.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "medplum.fullname" . }}
  namespace: {{ include "medplum.namespace" . }}
  labels:
    {{- include "medplum.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "medplum.fullname" . }}
  minReplicas: {{ .Values.deployment.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.deployment.autoscaling.maxReplicas | default 10 }}
  metrics:
    {{- $cpuThreshold := .Values.deployment.autoscaling.targetCPUUtilizationPercentage | default 80 }}
    {{- $memoryThreshold := .Values.deployment.autoscaling.targetMemoryUtilizationPercentage | default 70 }}
    {{- if or $cpuThreshold $memoryThreshold }}
    {{- if $cpuThreshold }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $cpuThreshold }}
    {{- end }}
    {{- if $memoryThreshold }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $memoryThreshold }}
    {{- end }}
    {{- else }}
    {{- fail "HPA requires at least one metric (CPU or Memory utilization threshold)" }}
    {{- end }}
{{- end }}

